### PR TITLE
New feature: HDBSCAN and DBSCAN in GUI

### PR DESCRIPTION
**Pull request by JohannaRahm**
With this new feature I want to make the clustering algorithms DBSCAN and HDBSCAN more accessible.

### Feature details:
- HDBSCAN is added to the Picasso command line
- DBSCAN & HDBSCAN are added to Picasso -> Render -> Postprocessing

Render_Postprocess_SCANS

### More Information:
existing code is added and linked into the Picasso framework:
- The code for HDBSCAN is taken from the SampleNotebook3 in the samples folder
- The code for the DBSCAN already existed in Picasso

### Tests:
I've tested the "new vs the existing ways":
existing way DBSCAN: python -m picasso dbscan ...
existing way HDBSCAN: SampleNotebook3
new way DBSCAN: GUI
new way HDBSCAN: GUI
new way HDBSCAN: python -m picasso hdbscan ...
- I compared the new and existing ways with two sets of parameters per cluster algorithm and executed the algorithm with one or multiple files at once.
- The resulting files (dbscan, dbcluster, yaml / hdbscan, hdbcluster, yaml) were always the same between the new and existing ways. 
### Other remarks:
- The docs are updated.
- HDBSCAN adds the necessary package hdbscan into postprocessing.py -> "Setting up the environment with conda, necessary packages" has to be updated.

What do you think about this new feature?
Best wishes J

### CODE REVIEW

**Comment by straussmaximilian** [comment]
Hi, 

Thank you very much for contributing.
I think this is fantastic work and fits nicely to the current codebase.
Additionally, I am very happy that you adapt the program to be used for your research work.  

Some more background for the hdbscan:
In the past, we had the hdbscan implemented, similar in the way you did. This, unfortunately, ended up crashing the creation of the one-click installer and I removed the functionality and instead used a notebook for that.  As the installer compilation is not working at this point anyhow and needs revision, I guess we are good to go. I think it makes a lot of sense to have it accessible in the GUI as functions in the command line often get overlooked.

As for the new feature, there are some things that I would recommend.

1) As you can see from the message above, the checks are currently failing, the reason being a module not found error `ModuleNotFoundError: No module named 'hdbscan'`. If you add new packages, you will need to add them to the `requirements.txt` additionally. This way, the checks should pass, and I can merge the pull request.

2) GUI-Implementation. One could think of making a new button named clustering where one could select the clustering method (e.g., via dropdown). This way, it would be much easier to implement additional clustering methods in the future.

3) Progress Completion:
Currently, there is no indication when the clustering is finished, which I think could be handy. This could be an additional print() output with maybe the path where the files were stored. For the GUI we could also have something like a QtWidgets.QMessageBox.information() to display.

With this regard, I am curious about your typical workflow: Do you do the clustering and then evaluate the summary statics or reload the clustering files back to render (I just noticed that for some reason, this is causing an IndexError - did you also experience that?).

Depending on that, one could also think about automatically loading the clustered file on completion or maybe show a graph with the summary statistics. Just some thoughts - what do you think?

Once again, thank you for your contribution. 

Best,

Max

**Comment by straussmaximilian** [comment]
Cool! Very nice.

**Comment by JohannaRahm** [comment]
Hey Max,

thanks for your feedback. I fully agree with you on the three points you made and added them. A message that is triggered when the algorithm terminates is a nice add on, because the computation might take a while.
I am able to reload the created dbscan file in Picasso-Render with no IndexError. However, in the workflow the dbcluster file is loaded in Picasso-Filter to make decisions about filter parameters based on the distributions and existing knowledge. The dbscan & dbcluster files are filtered with clusterfilter via the command line. Two drawbacks here: Only one filter parameter can be applied at once & the filter is applied to the dbscan file, not the dbclusters. To access a filtered dbcluster version, a clusteralgorithm runs over the final filtered dbscan file. A future feature could be the integration of the clusterfilter into Picasso-Filter with multi-parameter filtering being applied to both the dbscan and dbcluster file. What do you think about it?

Best regards,
Johanna

**Comment by straussmaximilian** [comment]
Hi Johanna,

That would be fantastic. A principal limitation for the clustering was always that they are somewhat disconnected from the localizations. The simple workaround that was implemented is the `clusterfilter` that comes with its limitations. 

I guess a proper implementation would allow Filter to load the hdf5 and the corresponding cluster file and perform filtering based on that (on that occasion I think it would also be super helpful to set limits in the Filter-GUI manually - or maybe even determine them somewhat automatically by applying a fit or so).  So very much aligned with what you suggested. 

Best,

Max

P.S.: The way the datasets are sliced is index-based. Some time ago, I wrote a [post](https://towardsdatascience.com/speeding-up-python-code-fast-filtering-and-slow-loops-8e11a09a9c2f) on different ways to do this. Maybe this could be useful here, especially for the multi-parameter case.

**Pull request merged**
