### PR TITLE
integration of gpufit

### PR DESCRIPTION
**Pull request by gpufit**
This commit adds an option to run the Levenberg-Marquardt fitting on a GPU, if available.  GPU-based fitting is performed using the Gpufit library (http://github.com/gpufit/gpufit).

### CODE REVIEW

**Comment by joschnitzbauer** [comment]
Haven't looked at Picasso code in a while, but the changes look reasonable to me. So, I recommend the merge, although @straussmaximilian should have the final word. Happy to see this contribution - thanks! :)

**Comment by straussmaximilian** [comment]
Hi,
I am on vacation until the end of the week and only have my Phone for internet access. I agree with Jörg the changes look reasonable - and thanks for the contribution. I'll have a look at it next week and provide you guys with feedback. I'm excited to see the GPU performance!

**Comment by superchromix** [comment]
Great!  For this modification to work, the pyGpufit module needs to be installed.  This is included with the binary distribution found in the "releases" section of the github site.  Another option is to build the Gpufit source code, which also causes the pyGpufit module to be created.

**Comment by straussmaximilian** [comment]
Hi, 
Unfortunately, we had some problems in getting a new GPU to fully test things out. Anyhow, I used an older PC now - with only a GTX970 and did some testing. The installation was straightforward. The performance gain is impressive:  For the test script that comes with the pyGPUfit package got a factor of 16 and in Picasso Localize the first tests showed a performance increase by a factor of ~50. I now merged the pull request.

**Pull request merged**
